import os
import numpy as np
import scipy.signal as signal
import matplotlib.pyplot as plt

# =========================================================================
# Advanced VLSI - Course Project
# Phase 1: FIR Filter Design, Quantization, and Test Vectors
# =========================================================================

def design_and_quantize():
    # ---------------------------------------------------------------------
    # 1. Filter Specifications
    # ---------------------------------------------------------------------
    Fpass = 0.2     # Passband edge (normalized to pi)
    Fstop = 0.23    # Stopband edge (normalized to pi)
    Apass = 1.0     # Passband ripple (dB)
    Astop = 80.0    # Minimum stopband attenuation (dB)
    
    # Calculate weights
    delta_pass = (10**(Apass/20)-1) / (10**(Apass/20)+1)
    delta_stop = 10**(-Astop/20)
    weight_stop = delta_pass / delta_stop # Note scipy remez uses inverted weight definition vs MATLAB firpm
    weights = [1.0, weight_stop]
    
    bands = [0, Fpass, Fstop, 1.0]
    desired = [1, 0]
    
    # ---------------------------------------------------------------------
    # 2. Iterate to find minimum taps for 80dB attenuation
    # ---------------------------------------------------------------------
    N = 100
    stopband_attenuation = 0
    h_ideal = None
    
    print("--- Filter Design ---")
    while True:
        # scipy.signal.remez designs the filter (same as firpm)
        h = signal.remez(N, bands, desired, weight=weights, fs=2.0)
        
        # Calculate frequency response
        w, h_freq = signal.freqz(h, worN=2048)
        w_norm = w / np.pi
        
        # Find minimum attenuation in stopband
        stop_indices = w_norm >= Fstop
        stopband_resp = 20 * np.log10(np.abs(h_freq[stop_indices]) + 1e-12)
        stopband_attenuation = -np.max(stopband_resp)
        
        if stopband_attenuation >= Astop:
            h_ideal = h
            print(f"Spec met with {N} taps (Attenuation = {stopband_attenuation:.2f} dB)")
            break
            
        N += 1
        if N > 200:
            print(f"Warning: Reached 200 taps without hitting spec (Current atten = {stopband_attenuation:.2f} dB)")
            h_ideal = h
            break
            
    # ---------------------------------------------------------------------
    # 3. Quantization
    # ---------------------------------------------------------------------
    print("\n--- Quantization ---")
    best_frac_bits = 8
    best_hq = None
    
    for frac_bits in range(8, 25):
        scale = 2**frac_bits
        hq = np.round(h_ideal * scale) / scale
        
        w_q, hq_freq = signal.freqz(hq, worN=2048)
        stop_resp_q = 20 * np.log10(np.abs(hq_freq[w_norm >= Fstop]) + 1e-12)
        attn_q = -np.max(stop_resp_q)
        
        print(f"Testing {frac_bits:2d} fractional bits: Attenuation = {attn_q:6.2f} dB")
        if attn_q >= Astop and best_hq is None:
            best_frac_bits = frac_bits
            best_hq = hq
            print(f">>> SPEC MET with {best_frac_bits} fractional bits! <<<")
            
    if best_hq is None:
        best_frac_bits = 24
        scale = 2**best_frac_bits
        best_hq = np.round(h_ideal * scale) / scale
        print("Warning: Could not meet spec. Using 24 bits.")
        
    # Integer values for RTL
    hq_int = np.round(best_hq * (2**best_frac_bits)).astype(np.int64)
    
    # ---------------------------------------------------------------------
    # 4. Datapath Widths
    # ---------------------------------------------------------------------
    input_bits = 16
    coeff_bits = 1 + best_frac_bits # 1 sign bit + fractional bits (no integer bits needed as coeffs are < 1)
    
    sum_abs_hq = np.sum(np.abs(best_hq))
    guard_bits = int(np.ceil(np.log2(sum_abs_hq)))
    
    acc_bits = input_bits + coeff_bits + int(np.ceil(np.log2(N))) + guard_bits
    
    print("\n--- Hardware Datapath Widths ---")
    print(f"Input Width:       {input_bits} bits")
    print(f"Coefficient Width: {coeff_bits} bits (Q1.{best_frac_bits})")
    print(f"Guard Bits:        {guard_bits} bits")
    print(f"Accumulator Width: {acc_bits} bits")
    
    # ---------------------------------------------------------------------
    # 5. Generate RTL Package
    # ---------------------------------------------------------------------
    rtl_dir = '../rtl'
    os.makedirs(rtl_dir, exist_ok=True)
    
    pkg_path = os.path.join(rtl_dir, 'coeff_pkg.sv')
    with open(pkg_path, 'w') as f:
        f.write("// Automatically generated by design_filter.py\n")
        f.write("package coeff_pkg;\n\n")
        f.write(f"  localparam int N_TAPS   = {N};\n")
        f.write(f"  localparam int COEFF_W  = {coeff_bits};\n")
        f.write(f"  localparam int DATA_W   = {input_bits};\n")
        f.write(f"  localparam int ACC_W    = {acc_bits};\n\n")
        f.write(f"  // {coeff_bits}-bit format (Q1.{best_frac_bits})\n")
        f.write(f"  localparam signed [COEFF_W-1:0] COEFFS [0:N_TAPS-1] = '{{\n")
        
        for i, val in enumerate(hq_int):
            # 2's complement hex string
            val_2c = val if val >= 0 else (val + (1 << coeff_bits))
            hex_w = (coeff_bits + 3) // 4
            hex_str = f"    {coeff_bits}'h{val_2c:0{hex_w}X}"
            
            if i < N - 1:
                f.write(f"{hex_str},\n")
            else:
                f.write(f"{hex_str}\n  }};\n\n")
                
        f.write("endpackage : coeff_pkg\n")
    print(f"Generated SystemVerilog package at {pkg_path}")
    
    # ---------------------------------------------------------------------
    # 6. Generate Test Vectors
    # ---------------------------------------------------------------------
    num_samples = 400
    n = np.arange(num_samples)
    max_input_val = (1 << (input_bits - 1)) - 1
    
    x_impulse = np.zeros(num_samples); x_impulse[0] = 1.0
    x_dc = 0.5 * np.ones(num_samples)
    
    f_pass = 0.1 / 2.0
    x_pass = 0.8 * np.sin(2 * np.pi * f_pass * n)
    
    f_stop = 0.5 / 2.0
    x_stop = 0.8 * np.sin(2 * np.pi * f_stop * n)
    
    f_trans = 0.215 / 2.0
    x_trans = 0.8 * np.sin(2 * np.pi * f_trans * n)
    
    x_noise = 0.1 * np.random.randn(num_samples)
    x_comp = 0.4*np.sin(2*np.pi*f_pass*n) + 0.4*np.sin(2*np.pi*f_stop*n) + x_noise
    x_comp = np.clip(x_comp, -1.0, 1.0)
    
    padding = np.zeros(N + 50)
    x_full = np.concatenate([
        x_impulse, padding, x_dc, padding, x_pass, padding, 
        x_stop, padding, x_trans, padding, x_comp, padding
    ])
    
    x_quant = np.round(x_full * max_input_val).astype(np.int64)
    x_quant = np.clip(x_quant, -max_input_val - 1, max_input_val)
    
    # Exact golden convolution
    y_golden_int = np.convolve(x_quant, hq_int)
    
    tb_dir = '../tb/test_vectors'
    os.makedirs(tb_dir, exist_ok=True)
    
    def write_hex(filename, data, bits):
        with open(filename, 'w') as f:
            for val in data:
                val_2c = val if val >= 0 else (val + (1 << bits))
                # Ensure it fits in 'bits' length
                val_2c &= ((1 << bits) - 1)
                hex_w = (bits + 3) // 4
                f.write(f"{val_2c:0{hex_w}X}\n")
                
    write_hex(os.path.join(tb_dir, 'input_stimulus.hex'), x_quant, input_bits)
    write_hex(os.path.join(tb_dir, 'golden_output.hex'), y_golden_int, acc_bits)
    
    with open(os.path.join(tb_dir, 'test_metadata.txt'), 'w') as f:
        f.write(f"NUM_SAMPLES = {len(x_quant)}\n")
        f.write("IMPULSE_START = 1\n")
        f.write(f"DC_START = {len(x_impulse) + len(padding) + 1}\n")
        f.write(f"PASSBAND_START = {len(x_impulse) + len(padding)*2 + len(x_dc) + 1}\n")
        f.write(f"STOPBAND_START = {len(x_impulse) + len(padding)*3 + len(x_dc) + len(x_pass) + 1}\n")
        
    print(f"Generated {len(x_quant)} test samples in {tb_dir}")
    
    # ---------------------------------------------------------------------
    # 7. Plotting
    # ---------------------------------------------------------------------
    plt.figure(figsize=(10, 8))
    
    # Freq Response
    plt.subplot(2, 1, 1)
    w_ideal, h_ideal_f = signal.freqz(h_ideal, worN=2048)
    w_quant, h_quant_f = signal.freqz(best_hq, worN=2048)
    
    plt.plot(w_ideal/np.pi, 20*np.log10(np.abs(h_ideal_f)+1e-12), 'b-', label='Ideal')
    plt.plot(w_quant/np.pi, 20*np.log10(np.abs(h_quant_f)+1e-12), 'r--', label=f'{coeff_bits}-bit Quantized')
    
    plt.axhline(-Astop, color='k', linestyle=':', label='Stopband Spec (-80dB)')
    plt.axvline(Fpass, color='g', linestyle=':', label='Passband')
    plt.axvline(Fstop, color='m', linestyle=':', label='Stopband')
    
    plt.title(f'FIR Filter Response (N={N})')
    plt.xlabel('Normalized Frequency (x pi rad/sample)')
    plt.ylabel('Magnitude (dB)')
    plt.ylim([-120, 10])
    plt.legend()
    plt.grid(True)
    
    # Time domain vectors
    plt.subplot(2, 1, 2)
    plt.plot(x_full)
    plt.title('Composite Test Stimulus')
    plt.xlabel('Samples')
    plt.ylabel('Amplitude')
    plt.grid(True)
    
    plt.tight_layout()
    plt.savefig('filter_design.png')
    print("Saved plots to filter_design.png")

if __name__ == "__main__":
    design_and_quantize()
