name: Build LaTeX Report

on:
  push:
    paths:
      - 'Final-DCT/report/**'
  pull_request:
    paths:
      - 'Final-DCT/report/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: Final-DCT/report/
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: Final-DCT-Report
          path: Final-DCT/report/main.pdf
