name: RTL Linting

on:
  push:
    paths:
      - 'Final-DCT/rtl/**'
      - 'Final-DCT/tb/**'
  pull_request:
    paths:
      - 'Final-DCT/rtl/**'
      - 'Final-DCT/tb/**'

jobs:
  verilator-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Verilator
        run: sudo apt-get update && sudo apt-get install -y verilator
      - name: Lint RTL and Testbenches
        run: verilator --lint-only -Wno-fatal -sv Final-DCT/rtl/*.sv Final-DCT/tb/*.sv
